include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    invalid_assignment: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    always_declare_return_types: true
    unnecessary_this: true
    use_super_parameters: true
    sort_constructors_first: true
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    lines_longer_than_80_chars: false
